version: "3.7"

services:
  cassandra:
    image: cassandra
  glowroot:
    image: glowroot/glowroot-central:0.13.5
    ports:
        - 4000:4000
        - 8181:8181
    depends_on:
      - cassandra