#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER $ARTIFACTORY_POSTGRES_USER WITH PASSWORD '$ARTIFACTORY_POSTGRES_PASSWORD';
    CREATE DATABASE artifactory;
    GRANT ALL PRIVILEGES ON DATABASE artifactory TO $ARTIFACTORY_POSTGRES_USER;
EOSQL