version: "3.7"

services:
  jenkins:
    image: jenkinsci/blueocean
    user: root
    volumes:
      - jenkins_home:/var/jenkins_home
      - release_packages:/repo/releases
      - maven_m2:/root/.m2
    ports:
      - 8080:8080
      - 50000:50000
  db:
    image: postgres:10.10
    restart: always
    environment:
      - POSTGRES_USER=${SONAR_POSTGRES_USER}
      - POSTGRES_PASSWORD=${SONAR_POSTGRES_PASSWORD}
      - ARTIFACTORY_POSTGRES_USER=${ARTIFACTORY_POSTGRES_USER}
      - ARTIFACTORY_POSTGRES_PASSWORD=${ARTIFACTORY_POSTGRES_PASSWORD}
    ports:
    - 5432:5432
    volumes:
      - ${POSTGRES_INIT}:/docker-entrypoint-initdb.d/
      - postgres_data:/var/lib/postgresql/data
  sonar:
    image: sonarqube
    depends_on:
      - db
    environment:
      - sonar.jdbc.url=jdbc:postgresql://db:5432/sonar
      - sonar.jdbc.username=${SONAR_POSTGRES_USER}
      - sonar.jdbc.password=${SONAR_POSTGRES_PASSWORD}
    ports:
      - 9000:9000
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions
      - ${SONAR_CONF}:/opt/sonarqube/conf
  artifactory:
    image: docker.bintray.io/jfrog/artifactory-oss
    depends_on:
      - db
    ports:
      - 8081:8081
    environment:
      - DB_TYPE=postgresql
      - DB_HOST=db
      - DB_USER=${ARTIFACTORY_POSTGRES_USER}
      - DB_PASSWORD=${ARTIFACTORY_POSTGRES_PASSWORD}
    volumes:
      - artifactory_data:/var/opt/jfrog/artifactory
    restart: always

volumes:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions:
  jenkins_home:
  release_packages:
  postgres_data:
  artifactory_data:
  maven_m2:
