version: "3.7"

services:
  cassandra:
    image: cassandra
  central:
  #   image: glowroot/glowroot-central:0.13.5
    build: central
    ports:
        - 4000:4000
        - 8181:8181
    depends_on:
      - cassandra
  app:
    build: sample-app
    ports:
      - 8082:8080