
build:
	docker-compose build

run:
	docker-compose up -d

stop:
	docker-compose stop

clean:
	docker-compose down

logs:
	docker-compose logs

tail:
	docker-compose logs -f

ps:
	docker-compose ps

volumes:
	docker volume ls
