version: "3.7"

services:
  jenkins:
    image: jenkinsci/blueocean
    user: root
    volumes:
      - jenkins_home:/var/jenkins_home
      - release_packages:/repo/releases
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 18080:8080
      - 50000:50000

volumes:
  jenkins_home:
  release_packages:
