version: "3.7"

services:
  neo4j:
    image: neo4j
    ports:
        - 7474:7474
        - 7687:7687
    volumes:
      - zeppelin_data:/data
    environment:
        - NEO4J_AUTH=neo4j/notebook
  zeppelin:
    image: apache/zeppelin:0.8.1
    # build: . ## For customizing Zeppelin configuration using config files.
    volumes:
      - zeppelin_work:/notebook
      - zeppelin_logs:/logs
      - zeppelin_data:/data
    ports:
      - 8088:8080
    environment:
      - ZEPPELIN_NOTEBOOK_DIR=/notebook
      - ZEPPELIN_LOG_DIR=/logs
      - ZEPPELIN_NOTEBOOK_GIT_REMOTE_URL=${ZEPPELIN_NOTEBOOK_GIT_REMOTE_URL}
      - ZEPPELIN_NOTEBOOK_GIT_REMOTE_ORIGIN=${ZEPPELIN_NOTEBOOK_GIT_REMOTE_ORIGIN}
      - ZEPPELIN_NOTEBOOK_GIT_REMOTE_USERNAME=${ZEPPELIN_NOTEBOOK_GIT_REMOTE_USERNAME}
      - ZEPPELIN_NOTEBOOK_GIT_REMOTE_ACCESS_TOKEN=${ZEPPELIN_NOTEBOOK_GIT_REMOTE_ACCESS_TOKEN}

volumes:
  zeppelin_work:
  zeppelin_logs:
  zeppelin_data:
