version: "3.7"

services:
  neo4j:
    image: neo4j
    ports:
        - 7474:7474
        - 7687:7687
    volumes:
      - neo4j_data:/data
      - shared_data:/var/lib/neo4j/import/
      - neo4j_plugins:/plugins
    environment:
        - NEO4J_AUTH=${NEO4J_AUTH}
        - NEO4J_apoc_export_file_enabled=true
        - NEO4J_apoc_import_file_enabled=true
        - NEO4J_apoc_import_file_use__neo4j__config=true
  zeppelin:
    image: apache/zeppelin:0.8.1
    # build: . ## For customizing Zeppelin configuration using config files.
    volumes:
      - zeppelin_work:/notebook
      - zeppelin_logs:/logs
      - shared_data:/data
      - neo4j_plugins:/neo4j/plugins
    ports:
      - 8088:8080
    environment:
      - ZEPPELIN_NOTEBOOK_DIR=/notebook
      - ZEPPELIN_LOG_DIR=/logs
      - ZEPPELIN_NOTEBOOK_GIT_REMOTE_URL=${ZEPPELIN_NOTEBOOK_GIT_REMOTE_URL}
      - ZEPPELIN_NOTEBOOK_GIT_REMOTE_ORIGIN=${ZEPPELIN_NOTEBOOK_GIT_REMOTE_ORIGIN}
      - ZEPPELIN_NOTEBOOK_GIT_REMOTE_USERNAME=${ZEPPELIN_NOTEBOOK_GIT_REMOTE_USERNAME}
      - ZEPPELIN_NOTEBOOK_GIT_REMOTE_ACCESS_TOKEN=${ZEPPELIN_NOTEBOOK_GIT_REMOTE_ACCESS_TOKEN}

volumes:
  zeppelin_work:
  zeppelin_logs:
  neo4j_data:
  shared_data:
  neo4j_plugins:
